Get-AppxPackage -AllUsers *3dBuilder* | Remove-AppxPackage
Get-AppxPackage -AllUsers *windowsalarms* | Remove-AppxPackage
Get-AppxPackage -AllUsers *windowscommunicationsapp* | Remove-AppxPackage
Get-AppxPackage -AllUsers *officehub* | Remove-AppxPackage
Get-AppxPackage -AllUsers *skypeapp* | Remove-AppxPackage
Get-AppxPackage -AllUsers *getstarted* | Remove-AppxPackage
Get-AppxPackage -AllUsers *zunemusic* | Remove-AppxPackage
Get-AppxPackage -AllUsers *windowsmaps* | Remove-AppxPackage
Get-AppxPackage -AllUsers *solitairecollection* | Remove-AppxPackage
Get-AppxPackage -AllUsers *bingfinance* | Remove-AppxPackage
Get-AppxPackage -AllUsers *bingnews* | Remove-AppxPackage
Get-AppxPackage -AllUsers *people* | Remove-AppxPackage
Get-AppxPackage -AllUsers *windowsphone* | Remove-AppxPackage
Get-AppxPackage -AllUsers *bingsports* | Remove-AppxPackage
Get-AppxPackage -AllUsers *soundrecorder* | Remove-AppxPackage
Get-AppxPackage -AllUsers *bingweather* | Remove-AppxPackage
Get-AppxPackage -AllUsers *king.com.CandyCrushSodaSaga* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Office.sway* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Twitter* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Bing* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.Messaging* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.BingFinance* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.WindowsScan* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.Reader* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.CommsPhone* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.ConnectivityStore* | Remove-AppxPackage
Get-AppxPackage -AllUsers *Microsoft.WindowsReadingList* | Remove-AppxPackage
